# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PayTaxi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PayTaxi
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Socket.IO-Client-Swift', '~> 13.1.0'
  pod 'Fabric'
  pod 'Crashlytics'
  
end

target 'PayTaxiDriver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PayTaxiDriver
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Socket.IO-Client-Swift', '~> 13.1.0'
  pod 'Fabric'
  pod 'Crashlytics'
  
end

target 'NotificationContent' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for PayTaxiDriver
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'Socket.IO-Client-Swift', '~> 13.1.0'
    pod 'Fabric'
    pod 'Crashlytics'
    
end

